export const CREATE_TASK = 'CREATE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const CLONE_TASK = 'CLONE_TASK'

export const TOGGLE_PRIORITY = 'TOGGLE_PRIORITY'
export const TOGGLE_COMPLETION = 'TOGGLE_COMPLETION'

export const COMPLETE_TASKS = 'COMPLETE_TASKS'
export const DELETE_TASKS = 'DELETE_TASKS'

export const CREATE_COMMENTS_KEY = 'CREATE_COMMENTS_KEY'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const CHECK_ALL = 'CHECK_ALL'
export const TOGGLE_CHECKLIST_ITEM = 'TOGGLE_CHECKLIST_ITEM'
export const CLONE_COMMENTS = 'CLONE_COMMENTS'