export const ADD_TASK = 'ADD_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const CLONE_TASK = 'CLONE_TASK'

export const TOGGLE_PRIORITY = 'TOGGLE_PRIORITY'
export const TOGGLE_COMPLETION = 'TOGGLE_COMPLETION'

export const COMPLETE_TASKS = 'COMPLETE_TASKS'
export const DELETE_TASKS = 'DELETE_TASKS'

export const CREATE_KEY = 'CREATE_KEY'
export const ADD_COMMENT = 'ADD_COMMENT'
export const CLONE_COMMENTS = 'CLONE_COMMENTS'